In [20]:
import pandas as pd 
dataset = pd.DataFrame({
                        "Weight":[65,68,52,79,55,60,71,55,85,100],
                        "Height":[180,176,195,210,155,168,170,188,150,145]
                        })
print(dataset)

   Weight  Height
0      65     180
1      68     176
2      52     195
3      79     210
4      55     155
5      60     168
6      71     170
7      55     188
8      85     150
9     100     145


Models to implement regression , scikit-learn

y = B0 + B1x

In [21]:
import pandas as Pd
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# dataset = pd.DataFrame({
#                         "Weight":[65,68,52,79,55,60,71,55,85,100],
#                         "Height":[180,176,195,210,155,168,170,188,150,145]
#                         })


Weight=Pd.DataFrame(dataset["Weight"])
Height =Pd.DataFrame(dataset["Height"])

model.fit(Weight,Height)

LinearRegression()

In [22]:
pred_values = model.predict(Weight)
print(pred_values)

[[175.96666667]
 [174.26666667]
 [183.33333333]
 [168.03333333]
 [181.63333333]
 [178.8       ]
 [172.56666667]
 [181.63333333]
 [164.63333333]
 [156.13333333]]


In [23]:
model.coef_  # B1


array([[-0.56666667]])

In [24]:
model.intercept_  # B0

array([212.8])

In [25]:
y = model.intercept_ + model.coef_*Weight
print(y)

       Weight
0  175.966667
1  174.266667
2  183.333333
3  168.033333
4  181.633333
5  178.800000
6  172.566667
7  181.633333
8  164.633333
9  156.133333


In [28]:
data = pd.read_csv("BostonHousing.csv")
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

   LSTAT  MEDV  CAT. MEDV  
0   4.98  24.0          0  
1   9.14  21.6          0  
2   4.03  34.7          1  
3   2.94  33.4          1  
4   5.33  36.2          1

In [30]:
data.shape

(506, 14)

Laso regression 

In [32]:
from sklearn import linear_model
from sklearn.linear_model import Lasso

lasso_reg = Lasso()

from sklearn.model_selection import train_test_split

depVarriable = "MEDV"
indepVarriables = data.columns.tolist()
indepVarriables.remove(depVarriable)
indepVarriables

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'LSTAT',
 'CAT. MEDV']

In [33]:
depVarriable

'MEDV'

In [38]:
from sklearn import datasets
# datasets.load_boston()


x = data[indepVarriables].values
y = data[depVarriable].values

print(x)


[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 4.9800e+00 0.0000e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 9.1400e+00 0.0000e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 4.0300e+00 1.0000e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 5.6400e+00 0.0000e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 6.4800e+00 0.0000e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 7.8800e+00 0.0000e+00]]


In [37]:
print(y)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [40]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101)

In [41]:
lasso_reg.fit(X_train, y_train)

Lasso()

In [43]:
predictions = lasso_reg.predict(X_test)
print(predictions)

[36.23595302 28.3452233  19.3223567  18.25215647 31.33910473 30.39979733
 33.33016255  7.89612714 33.02573351  7.26102559 30.08648415 13.18680522
 19.90256105 21.58289209 24.43622577 22.28683647  8.74277899 31.91334204
 27.43655488 25.86469959 13.06982669 20.33663377 25.1158355  26.25227067
 32.55741523 20.62776936 27.74341135 18.37475137 25.87040271 31.73606047
 22.2635923  21.22480736 34.8591109  36.78736194 27.88999707 22.38179254
 17.27597654 20.46181203  3.61737556 31.6334418  24.32670426 22.98520725
 30.87294879 14.85960671 18.88910156 25.68759614 28.89273891 15.71145901
 26.85732399 25.12368441 31.36809635 29.60693775 23.14934268 21.61041932
 30.38189862 -0.33085421 19.71756934 16.0047048  19.0051248  20.14365875
 29.67751569  1.92721758 25.13496996 21.27760555 11.57345204 23.56706785
 24.2123773  20.9812837  15.04139348 21.79796276 24.07931333 24.81317939
 23.16662141 20.51875837 26.67171197 22.8071942  35.49536253  6.9852506
 29.70467289 15.63534407 17.42383094 20.19682527 29.

In [47]:
coeffs = lasso_reg.coef_
print(coeffs)

[-0.06032357  0.04032443 -0.          0.         -0.          0.61141653
  0.02468502 -0.60855879  0.22081785 -0.01308099 -0.64362572 -0.82872107
  0.66678408]


In [45]:
lasso_reg.intercept_

np.float64(44.35849683615106)

In [48]:
from sklearn.metrics import mean_squared_error, r2_score
r2_score(y_test, predictions)

0.6586389513087358

ridge regression

In [ ]:
from sklearn import linear_model
from sklearn.linear_model import Ridge

ridge_reg = Ridge()
ridge_reg.fit(X_train, y_train)



Ridge()

In [50]:
predictions = ridge_reg.predict(X_test)
print(predictions)

[40.67157592 36.2051457  17.34538736 17.37906494 36.34474113 37.48999508
 41.38245326 11.04396494 39.28590727  7.48721521 24.71208508 14.6662709
 18.95061739 17.97680644 22.38215375 19.22034771  9.40948107 26.4675769
 25.19988059 23.64432452 13.12191916 19.63070952 22.16436624 24.22216169
 37.74959409 18.61195056 27.46048084 18.44610019 34.95863943 36.87463185
 20.41289163 19.36678555 39.10233075 43.29316164 34.74132231 22.14463194
 17.30027646 18.47907975  7.43799946 37.43709307 22.31489603 18.02711228
 39.67157107 14.29012062 18.6797371  23.10650541 26.23478438 16.53264852
 23.59269743 33.00386565 38.53396884 29.88228375 21.36497923 16.30416959
 37.93466631  3.09844115 19.23173768 16.37873809 21.54946303 20.11199193
 34.93006689  6.70897229 18.96888529 18.05000037 12.41609698 22.14340592
 23.16034774 19.27851024 15.36395208 19.90624002 21.80587412 22.46018945
 21.85798443 19.71196457 25.29356266 21.78268612 41.51680022 10.18146131
 25.82253578 15.42439277 16.55997804 18.70893492 26.7

In [51]:
intercept = ridge_reg.intercept_
print(intercept)

35.829126364899096


In [52]:
r2_score(y_test, predictions)

0.822550791936557